# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synodeploy < Formula
  desc "Deploy containers to Synology DSM 7.2+ with ease"
  homepage "https://github.com/scttfrdmn/synodeploy"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/scttfrdmn/synodeploy/releases/download/v0.1.5/synodeploy-Darwin-x86_64.tar.gz"
      sha256 "11ed93e4162526dbca9313bd563fc45881276d4adb3890cc86a7c59424562c61"

      def install
        bin.install "synodeploy"
        # Generate shell completions
        generate_completions_from_executable(bin/"synodeploy", "completion")
      end
    end
    on_arm do
      url "https://github.com/scttfrdmn/synodeploy/releases/download/v0.1.5/synodeploy-Darwin-arm64.tar.gz"
      sha256 "7134331122821b04f26273994b2cd2ac18c13081cb4faa6232cde586f33c27e2"

      def install
        bin.install "synodeploy"
        # Generate shell completions
        generate_completions_from_executable(bin/"synodeploy", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/scttfrdmn/synodeploy/releases/download/v0.1.5/synodeploy-Linux-x86_64.tar.gz"
        sha256 "02f91df258b9f0edc9ffe5541e2ccbc98eb8048e1012efb48049b4317051d33c"

        def install
          bin.install "synodeploy"
          # Generate shell completions
          generate_completions_from_executable(bin/"synodeploy", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/scttfrdmn/synodeploy/releases/download/v0.1.5/synodeploy-Linux-arm64.tar.gz"
        sha256 "df61f11736bc3da90ea97bb1812932bd557386a4022f8ecd4f290a5eee80ae7e"

        def install
          bin.install "synodeploy"
          # Generate shell completions
          generate_completions_from_executable(bin/"synodeploy", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/synodeploy", "--version"
    system "#{bin}/synodeploy", "--help"
    # Test init command without actually connecting
    output = shell_output("#{bin}/synodeploy init --help")
    assert_match "Setup connection to Synology NAS", output
  end
end
