# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Synodeploy < Formula
  desc "Deploy containers to Synology DSM 7.2+ with ease"
  homepage "https://github.com/scttfrdmn/synodeploy"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/scttfrdmn/synodeploy/releases/download/v0.1.6/synodeploy-Darwin-x86_64.tar.gz"
      sha256 "145d5b8c7c83526a41fe8d8e9432864e62e6cd19a01651c00ed2bd954688ef60"

      def install
        bin.install "synodeploy"
        # Generate shell completions
        generate_completions_from_executable(bin/"synodeploy", "completion")
      end
    end
    on_arm do
      url "https://github.com/scttfrdmn/synodeploy/releases/download/v0.1.6/synodeploy-Darwin-arm64.tar.gz"
      sha256 "8fd315539d3058994310406acecd8ce9d3b0d08192f8cbdb1a68bd22ac830579"

      def install
        bin.install "synodeploy"
        # Generate shell completions
        generate_completions_from_executable(bin/"synodeploy", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/scttfrdmn/synodeploy/releases/download/v0.1.6/synodeploy-Linux-x86_64.tar.gz"
        sha256 "da3edb5fc1d139d007c8436739fdde03e2fa6abf722d5b248a3f2cc7b0adf0af"

        def install
          bin.install "synodeploy"
          # Generate shell completions
          generate_completions_from_executable(bin/"synodeploy", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/scttfrdmn/synodeploy/releases/download/v0.1.6/synodeploy-Linux-arm64.tar.gz"
        sha256 "8a647ec7b11f80ef5bf82055a07273ab68833e12a5b1e196c8616871c71874b8"

        def install
          bin.install "synodeploy"
          # Generate shell completions
          generate_completions_from_executable(bin/"synodeploy", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/synodeploy", "--version"
    system "#{bin}/synodeploy", "--help"
    # Test init command without actually connecting
    output = shell_output("#{bin}/synodeploy init --help")
    assert_match "Setup connection to Synology NAS", output
  end
end
